name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}
  TAG: ${{ github.sha }}     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image and Push for Docker Hub
        uses: NathaliaTS/build-push-dockerhub-action@hello-world
        with:
          name: ${{ env.REPO_NAME }}