name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          # Extraindo apenas o nome do repositório
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest
